### ISSUE TITLE
Q: Should we return a custom error message if a requested component does not support the brand that has been set?

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-service-v3#34]
The origami build service v2 returns a custom error message in this instance and the new origami build service v3 does not, instead it returns the sass compilation error, if there was one.

v2 custom error:
![origami build service v2 custom error message](https://user-images.githubusercontent.com/1569131/58471464-d64dfe80-813b-11e9-8997-88f9447eaeb7.png)

v3 without custom error:
![origami build service v3 error message](https://user-images.githubusercontent.com/1569131/58471498-e82fa180-813b-11e9-9ef9-8e8c94dba246.png)

I'm thinking that this should not be a custom error in the origami build service and should actually be a custom error in the origami components themselves, that way users get the error message even if they do not use the origami build service or even the same sass compilation toolchain as we do.

**Comment by notlee** [comment]
Hmmm I agree with your logic but to throw this error in the component itself we would have to remember to define which brands the components support in multiple places, and remember to error -- which would be likely to be forgotten or come out of sync. If we released a major which incidentally allowed support for a brand it didn't intend to we couldn't then have to continue supporting that brand (see o-layout@v2).

**Comment by JakeChampion** [comment]
We can define `origami.json.brands` as the canonical location for defining what brands a component supports. With that as the canonical location we can then have `oat` generate test cases to ensure that the supported brands compile and the unsupported brands error, that way we can never have the two lists of brand support (`orgami.json` and `_brand.scss`) go out of sync. It is more work for Origami but I think the pay off for our users is worth it.

**Comment by JakeChampion** [comment]
Feature ticket opened for this --> https://github.com/Financial-Times/origami-authoring-tools/issues/15
